In [2]:
import pandas as pd

In [3]:
# Importing csv

storm_csv = pd.read_csv('data/Storms_2020.csv')
storm_csv.head()

C:\Users\ana_m\anaconda3\envs\PythonData\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (16,17,20) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,event_id,state,event_type,cz_name,event_begin_time,event_timezone,event_end_time,injuries_direct,injuries_indirect,deaths_direct,...,tor_length,tor_width,tor_other_wfo,location_index,event_range,event_azimuth,reference_location,event_latitude,event_longitude,event_point
0,865452,Oklahoma,hail,TULSA,1/10/2020 11:35,CST-6,1/10/2020 11:35,0,0,0,...,NaN,0,NaN,1.0,0.24,ENE,TULSA,36.1514,-95.9460,POINT(-95.946 36.1514)
1,865453,Oklahoma,hail,TULSA,1/10/2020 11:36,CST-6,1/10/2020 11:36,0,0,0,...,NaN,0,NaN,1.0,2.95,NNE,TULSA R L JONES ARPT,36.0690,-95.9585,POINT(-95.9585 36.069)
2,865454,Oklahoma,hail,TULSA,1/10/2020 11:38,CST-6,1/10/2020 11:38,0,0,0,...,NaN,0,NaN,1.0,2.00,N,TULSA,36.1790,-95.9500,POINT(-95.95 36.179)
3,865455,Oklahoma,hail,CHEROKEE,1/10/2020 15:02,CST-6,1/10/2020 15:02,0,0,0,...,NaN,0,NaN,1.0,0.65,S,TAHLEQUAH,35.9106,-94.9710,POINT(-94.971 35.9106)
4,865712,Texas,hail,HAYS,1/10/2020 19:40,CST-6,1/10/2020 19:40,0,0,0,...,NaN,0,NaN,1.0,5.01,ENE,HENLY,30.2400,-98.1500,POINT(-98.15 30.24)

In [4]:
storm_csv.columns

Index(['event_id', 'state', 'event_type', 'cz_name', 'event_begin_time',
       'event_timezone', 'event_end_time', 'injuries_direct',
       'injuries_indirect', 'deaths_direct', 'deaths_indirect',
       'damage_property', 'damage_crops', 'source', 'magnitude',
       'magnitude_type', 'flood_cause', 'tor_f_scale', 'tor_length',
       'tor_width', 'tor_other_wfo', 'location_index', 'event_range',
       'event_azimuth', 'reference_location', 'event_latitude',
       'event_longitude', 'event_point'],
      dtype='object')

In [5]:
# selecting the columns we want

new_stormcsv = storm_csv[['event_id', 'state', 'event_type','event_begin_time',
       'event_timezone', 'event_end_time','injuries_direct',
       'injuries_indirect', 'deaths_direct', 'deaths_indirect',
       'damage_property', 'damage_crops','magnitude','event_latitude',
       'event_longitude']]
new_stormcsv.head()

,event_id,state,event_type,event_begin_time,event_timezone,event_end_time,injuries_direct,injuries_indirect,deaths_direct,deaths_indirect,damage_property,damage_crops,magnitude,event_latitude,event_longitude
0,865452,Oklahoma,hail,1/10/2020 11:35,CST-6,1/10/2020 11:35,0,0,0,0,0.0,0.0,1.00,36.1514,-95.9460
1,865453,Oklahoma,hail,1/10/2020 11:36,CST-6,1/10/2020 11:36,0,0,0,0,0.0,0.0,1.00,36.0690,-95.9585
2,865454,Oklahoma,hail,1/10/2020 11:38,CST-6,1/10/2020 11:38,0,0,0,0,0.0,0.0,0.75,36.1790,-95.9500
3,865455,Oklahoma,hail,1/10/2020 15:02,CST-6,1/10/2020 15:02,0,0,0,0,15000.0,0.0,1.75,35.9106,-94.9710
4,865712,Texas,hail,1/10/2020 19:40,CST-6,1/10/2020 19:40,0,0,0,0,0.0,0.0,0.75,30.2400,-98.1500

In [11]:
#identifying types for each column
new_stormcsv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40037 entries, 0 to 40036
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   event_id           40037 non-null  int64
 1   state              40037 non-null  object
 2   event_type         40037 non-null  object
 3   event_begin_time   40037 non-null  object
 4   event_timezone     40037 non-null  object
 5   event_end_time     40037 non-null  object
 6   injuries_direct    40037 non-null  int64
 7   injuries_indirect  40037 non-null  int64
 8   deaths_direct      40037 non-null  int64
 9   deaths_indirect    40037 non-null  int64
 10  damage_property    31453 non-null  float64
 11  damage_crops       32222 non-null  float64
 12  magnitude          25659 non-null  float64
 13  event_latitude     25669 non-null  float64
 14  event_longitude    25669 non-null  float64
dtypes: float64(5), int64(5), object(5)
memory usage: 4.6+ MB

In [15]:
# cleaning date columns

new_stormcsv['event_begin_time'] = pd.to_datetime(new_stormcsv['event_begin_time'])
new_stormcsv['event_end_time'] = pd.to_datetime(new_stormcsv['event_end_time'])

<ipython-input-15-5d2f0f95d151>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_stormcsv['event_begin_time'] = pd.to_datetime(new_stormcsv['event_begin_time'])
<ipython-input-15-5d2f0f95d151>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_stormcsv['event_end_time'] = pd.to_datetime(new_stormcsv['event_end_time'])

In [16]:
new_stormcsv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40037 entries, 0 to 40036
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   event_id           40037 non-null  int64
 1   state              40037 non-null  object
 2   event_type         40037 non-null  object
 3   event_begin_time   40037 non-null  datetime64[ns]
 4   event_timezone     40037 non-null  object
 5   event_end_time     40037 non-null  datetime64[ns]
 6   injuries_direct    40037 non-null  int64
 7   injuries_indirect  40037 non-null  int64
 8   deaths_direct      40037 non-null  int64
 9   deaths_indirect    40037 non-null  int64
 10  damage_property    31453 non-null  float64
 11  damage_crops       32222 non-null  float64
 12  magnitude          25659 non-null  float64
 13  event_latitude     25669 non-null  float64
 14  event_longitude    25669 non-null  float64
dtypes: datetime64[ns](2), float64(5), int64(5), object(3)
memory usage: 4.6+ MB

In [17]:
# Combining injury and death columns to be one

new_stormcsv['Injuries'] = new_stormcsv['injuries_direct'] + new_stormcsv['injuries_indirect']
new_stormcsv['Deaths'] = new_stormcsv['deaths_direct'] + new_stormcsv['deaths_indirect']
new_stormcsv.head()

<ipython-input-17-efc3a3b93e84>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_stormcsv['Injuries'] = new_stormcsv['injuries_direct'] + new_stormcsv['injuries_indirect']
<ipython-input-17-efc3a3b93e84>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_stormcsv['Deaths'] = new_stormcsv['deaths_direct'] + new_stormcsv['deaths_indirect']

,event_id,state,event_type,event_begin_time,event_timezone,event_end_time,injuries_direct,injuries_indirect,deaths_direct,deaths_indirect,damage_property,damage_crops,magnitude,event_latitude,event_longitude,Injuries,Deaths
0,865452,Oklahoma,hail,2020-01-10 11:35:00,CST-6,2020-01-10 11:35:00,0,0,0,0,0.0,0.0,1.00,36.1514,-95.9460,0,0
1,865453,Oklahoma,hail,2020-01-10 11:36:00,CST-6,2020-01-10 11:36:00,0,0,0,0,0.0,0.0,1.00,36.0690,-95.9585,0,0
2,865454,Oklahoma,hail,2020-01-10 11:38:00,CST-6,2020-01-10 11:38:00,0,0,0,0,0.0,0.0,0.75,36.1790,-95.9500,0,0
3,865455,Oklahoma,hail,2020-01-10 15:02:00,CST-6,2020-01-10 15:02:00,0,0,0,0,15000.0,0.0,1.75,35.9106,-94.9710,0,0
4,865712,Texas,hail,2020-01-10 19:40:00,CST-6,2020-01-10 19:40:00,0,0,0,0,0.0,0.0,0.75,30.2400,-98.1500,0,0

In [18]:
new_stormcsv.columns

Index(['event_id', 'state', 'event_type', 'event_begin_time', 'event_timezone',
       'event_end_time', 'injuries_direct', 'injuries_indirect',
       'deaths_direct', 'deaths_indirect', 'damage_property', 'damage_crops',
       'magnitude', 'event_latitude', 'event_longitude', 'Injuries', 'Deaths'],
      dtype='object')

In [24]:
clean_storm = new_stormcsv[['event_id', 'state', 'event_type', 'event_begin_time', 'event_timezone',
       'event_end_time', 'Injuries', 'Deaths', 'damage_property', 'damage_crops',
       'magnitude', 'event_latitude', 'event_longitude']]
clean_storm.head()

,event_id,state,event_type,event_begin_time,event_timezone,event_end_time,Injuries,Deaths,damage_property,damage_crops,magnitude,event_latitude,event_longitude
0,865452,Oklahoma,hail,2020-01-10 11:35:00,CST-6,2020-01-10 11:35:00,0,0,0.0,0.0,1.00,36.1514,-95.9460
1,865453,Oklahoma,hail,2020-01-10 11:36:00,CST-6,2020-01-10 11:36:00,0,0,0.0,0.0,1.00,36.0690,-95.9585
2,865454,Oklahoma,hail,2020-01-10 11:38:00,CST-6,2020-01-10 11:38:00,0,0,0.0,0.0,0.75,36.1790,-95.9500
3,865455,Oklahoma,hail,2020-01-10 15:02:00,CST-6,2020-01-10 15:02:00,0,0,15000.0,0.0,1.75,35.9106,-94.9710
4,865712,Texas,hail,2020-01-10 19:40:00,CST-6,2020-01-10 19:40:00,0,0,0.0,0.0,0.75,30.2400,-98.1500

In [26]:
# column renamings

clean_storm = clean_storm.rename(columns={'Injuries':'total_injuries', 'Deaths':'total_deaths'})
clean_storm.head()

,event_id,state,event_type,event_begin_time,event_timezone,event_end_time,total_injuries,total_deaths,damage_property,damage_crops,magnitude,event_latitude,event_longitude
0,865452,Oklahoma,hail,2020-01-10 11:35:00,CST-6,2020-01-10 11:35:00,0,0,0.0,0.0,1.00,36.1514,-95.9460
1,865453,Oklahoma,hail,2020-01-10 11:36:00,CST-6,2020-01-10 11:36:00,0,0,0.0,0.0,1.00,36.0690,-95.9585
2,865454,Oklahoma,hail,2020-01-10 11:38:00,CST-6,2020-01-10 11:38:00,0,0,0.0,0.0,0.75,36.1790,-95.9500
3,865455,Oklahoma,hail,2020-01-10 15:02:00,CST-6,2020-01-10 15:02:00,0,0,15000.0,0.0,1.75,35.9106,-94.9710
4,865712,Texas,hail,2020-01-10 19:40:00,CST-6,2020-01-10 19:40:00,0,0,0.0,0.0,0.75,30.2400,-98.1500

In [27]:
clean_storm.dropna()
clean_storm.head()

,event_id,state,event_type,event_begin_time,event_timezone,event_end_time,total_injuries,total_deaths,damage_property,damage_crops,magnitude,event_latitude,event_longitude
0,865452,Oklahoma,hail,2020-01-10 11:35:00,CST-6,2020-01-10 11:35:00,0,0,0.0,0.0,1.00,36.1514,-95.9460
1,865453,Oklahoma,hail,2020-01-10 11:36:00,CST-6,2020-01-10 11:36:00,0,0,0.0,0.0,1.00,36.0690,-95.9585
2,865454,Oklahoma,hail,2020-01-10 11:38:00,CST-6,2020-01-10 11:38:00,0,0,0.0,0.0,0.75,36.1790,-95.9500
3,865455,Oklahoma,hail,2020-01-10 15:02:00,CST-6,2020-01-10 15:02:00,0,0,15000.0,0.0,1.75,35.9106,-94.9710
4,865712,Texas,hail,2020-01-10 19:40:00,CST-6,2020-01-10 19:40:00,0,0,0.0,0.0,0.75,30.2400,-98.1500

In [ ]:
# linking to ETL project DB created on Marcus' local
conn = "postgres:postgres@localhost:5432/ETLproject"
engine = create_engine(f'postgresql://{conn}')