In [1]:
import pandas as pd
from sqlalchemy import create_engine 
import datetime as dt

In [2]:
# Importing csv

storm_csv = pd.read_csv('data/Storms_2020.csv')
storm_csv.head()

C:\Users\ana_m\anaconda3\envs\PythonData\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (16,17,20) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,event_id,state,event_type,cz_name,event_begin_time,event_timezone,event_end_time,injuries_direct,injuries_indirect,deaths_direct,...,tor_length,tor_width,tor_other_wfo,location_index,event_range,event_azimuth,reference_location,event_latitude,event_longitude,event_point
0,865452,Oklahoma,hail,TULSA,1/10/2020 11:35,CST-6,1/10/2020 11:35,0,0,0,...,NaN,0,NaN,1.0,0.24,ENE,TULSA,36.1514,-95.9460,POINT(-95.946 36.1514)
1,865453,Oklahoma,hail,TULSA,1/10/2020 11:36,CST-6,1/10/2020 11:36,0,0,0,...,NaN,0,NaN,1.0,2.95,NNE,TULSA R L JONES ARPT,36.0690,-95.9585,POINT(-95.9585 36.069)
2,865454,Oklahoma,hail,TULSA,1/10/2020 11:38,CST-6,1/10/2020 11:38,0,0,0,...,NaN,0,NaN,1.0,2.00,N,TULSA,36.1790,-95.9500,POINT(-95.95 36.179)
3,865455,Oklahoma,hail,CHEROKEE,1/10/2020 15:02,CST-6,1/10/2020 15:02,0,0,0,...,NaN,0,NaN,1.0,0.65,S,TAHLEQUAH,35.9106,-94.9710,POINT(-94.971 35.9106)
4,865712,Texas,hail,HAYS,1/10/2020 19:40,CST-6,1/10/2020 19:40,0,0,0,...,NaN,0,NaN,1.0,5.01,ENE,HENLY,30.2400,-98.1500,POINT(-98.15 30.24)

In [3]:
storm_csv.columns

Index(['event_id', 'state', 'event_type', 'cz_name', 'event_begin_time',
       'event_timezone', 'event_end_time', 'injuries_direct',
       'injuries_indirect', 'deaths_direct', 'deaths_indirect',
       'damage_property', 'damage_crops', 'source', 'magnitude',
       'magnitude_type', 'flood_cause', 'tor_f_scale', 'tor_length',
       'tor_width', 'tor_other_wfo', 'location_index', 'event_range',
       'event_azimuth', 'reference_location', 'event_latitude',
       'event_longitude', 'event_point'],
      dtype='object')

In [4]:
# selecting the columns we want

new_stormcsv = storm_csv[['event_id', 'state', 'event_type','event_begin_time',
       'event_timezone', 'event_end_time','injuries_direct',
       'injuries_indirect', 'deaths_direct', 'deaths_indirect',
       'damage_property', 'damage_crops','magnitude','event_latitude',
       'event_longitude']]
new_stormcsv.head()

,event_id,state,event_type,event_begin_time,event_timezone,event_end_time,injuries_direct,injuries_indirect,deaths_direct,deaths_indirect,damage_property,damage_crops,magnitude,event_latitude,event_longitude
0,865452,Oklahoma,hail,1/10/2020 11:35,CST-6,1/10/2020 11:35,0,0,0,0,0.0,0.0,1.00,36.1514,-95.9460
1,865453,Oklahoma,hail,1/10/2020 11:36,CST-6,1/10/2020 11:36,0,0,0,0,0.0,0.0,1.00,36.0690,-95.9585
2,865454,Oklahoma,hail,1/10/2020 11:38,CST-6,1/10/2020 11:38,0,0,0,0,0.0,0.0,0.75,36.1790,-95.9500
3,865455,Oklahoma,hail,1/10/2020 15:02,CST-6,1/10/2020 15:02,0,0,0,0,15000.0,0.0,1.75,35.9106,-94.9710
4,865712,Texas,hail,1/10/2020 19:40,CST-6,1/10/2020 19:40,0,0,0,0,0.0,0.0,0.75,30.2400,-98.1500

In [5]:
#identifying types for each column
new_stormcsv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40037 entries, 0 to 40036
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   event_id           40037 non-null  int64
 1   state              40037 non-null  object
 2   event_type         40037 non-null  object
 3   event_begin_time   40037 non-null  object
 4   event_timezone     40037 non-null  object
 5   event_end_time     40037 non-null  object
 6   injuries_direct    40037 non-null  int64
 7   injuries_indirect  40037 non-null  int64
 8   deaths_direct      40037 non-null  int64
 9   deaths_indirect    40037 non-null  int64
 10  damage_property    31453 non-null  float64
 11  damage_crops       32222 non-null  float64
 12  magnitude          25659 non-null  float64
 13  event_latitude     25669 non-null  float64
 14  event_longitude    25669 non-null  float64
dtypes: float64(5), int64(5), object(5)
memory usage: 4.6+ MB

In [6]:
# cleaning date columns

new_stormcsv['event_begin_time'] = pd.to_datetime(new_stormcsv['event_begin_time'])
new_stormcsv['event_end_time'] = pd.to_datetime(new_stormcsv['event_end_time'])

<ipython-input-6-5d2f0f95d151>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_stormcsv['event_begin_time'] = pd.to_datetime(new_stormcsv['event_begin_time'])
<ipython-input-6-5d2f0f95d151>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_stormcsv['event_end_time'] = pd.to_datetime(new_stormcsv['event_end_time'])

In [7]:
new_stormcsv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40037 entries, 0 to 40036
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   event_id           40037 non-null  int64
 1   state              40037 non-null  object
 2   event_type         40037 non-null  object
 3   event_begin_time   40037 non-null  datetime64[ns]
 4   event_timezone     40037 non-null  object
 5   event_end_time     40037 non-null  datetime64[ns]
 6   injuries_direct    40037 non-null  int64
 7   injuries_indirect  40037 non-null  int64
 8   deaths_direct      40037 non-null  int64
 9   deaths_indirect    40037 non-null  int64
 10  damage_property    31453 non-null  float64
 11  damage_crops       32222 non-null  float64
 12  magnitude          25659 non-null  float64
 13  event_latitude     25669 non-null  float64
 14  event_longitude    25669 non-null  float64
dtypes: datetime64[ns](2), float64(5), int64(5), object(3)
memory usage: 4.6+ MB

In [8]:
# Combining injury and death columns to be one

new_stormcsv['Injuries'] = new_stormcsv['injuries_direct'] + new_stormcsv['injuries_indirect']
new_stormcsv['Deaths'] = new_stormcsv['deaths_direct'] + new_stormcsv['deaths_indirect']
# new_stormcsv['event_month'] = dt.datetime.strftime(new_stormcsv['event_begin_time'], "%m")
new_stormcsv['event_month'] = new_stormcsv['event_begin_time'].dt.month
new_stormcsv.tail(30)

<ipython-input-8-5c9a2ca17e29>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_stormcsv['Injuries'] = new_stormcsv['injuries_direct'] + new_stormcsv['injuries_indirect']
<ipython-input-8-5c9a2ca17e29>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_stormcsv['Deaths'] = new_stormcsv['deaths_direct'] + new_stormcsv['deaths_indirect']
<ipython-input-8-5c9a2ca17e29>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_stormcsv['event_month'] = new_stormcsv['event_begin_time'].dt.month

,event_id,state,event_type,event_begin_time,event_timezone,event_end_time,injuries_direct,injuries_indirect,deaths_direct,deaths_indirect,damage_property,damage_crops,magnitude,event_latitude,event_longitude,Injuries,Deaths,event_month
40007,913791,Gulf of mexico,marine thunderstorm wind,2020-07-21 02:20:00,EST-5,2020-07-21 02:20:00,0,0,0,0,0.0,0.0,41.0,24.8430,-80.8620,0,0,7
40008,913817,Gulf of mexico,marine thunderstorm wind,2020-07-21 11:45:00,EST-5,2020-07-21 11:45:00,0,0,0,0,0.0,0.0,35.0,24.7200,-81.9200,0,0,7
40009,913792,Gulf of mexico,marine thunderstorm wind,2020-07-21 02:40:00,EST-5,2020-07-21 02:40:00,0,0,0,0,0.0,0.0,34.0,24.6280,-81.1090,0,0,7
40010,913854,Gulf of mexico,marine thunderstorm wind,2020-07-23 10:00:00,EST-5,2020-07-23 10:00:00,0,0,0,0,0.0,0.0,38.0,24.7200,-81.9200,0,0,7
40011,913861,Gulf of mexico,marine thunderstorm wind,2020-07-24 01:40:00,EST-5,2020-07-24 01:40:00,0,0,0,0,0.0,0.0,35.0,24.4560,-81.8770,0,0,7
40012,913856,Gulf of mexico,marine thunderstorm wind,2020-07-23 14:56:00,EST-5,2020-07-23 14:56:00,0,0,0,0,0.0,0.0,39.0,24.8500,-80.6200,0,0,7
40013,913858,Gulf of mexico,marine thunderstorm wind,2020-07-23 16:00:00,EST-5,2020-07-23 16:00:00,0,0,0,0,0.0,0.0,36.0,24.4560,-81.8770,0,0,7
40014,913855,Gulf of mexico,marine thunderstorm wind,2020-07-23 13:30:00,EST-5,2020-07-23 13:30:00,0,0,0,0,0.0,0.0,34.0,24.4560,-81.8770,0,0,7
40015,913860,Gulf of mexico,marine thunderstorm wind,2020-07-23 17:30:00,EST-5,2020-07-23 17:30:00,0,0,0,0,0.0,0.0,34.0,24.7200,-81.9200,0,0,7
40016,913852,Gulf of mexico,marine thunderstorm wind,2020-07-23 09:32:00,EST-5,2020-07-23 09:32:00,0,0,0,0,0.0,0.0,35.0,24.5532,-81.7886,0,0,7
40017,913853,Gulf of mexico,marine thunderstorm wind,2020-07-23 10:00:00,EST-5,2020-07-23 10:00:00,0,0,0,0,0.0,0.0,35.0,24.5638,-81.7343,0,0,7
40018,913862,Gulf of mexico,marine thunderstorm wind,2020-07-24 22:31:00,EST-5,2020-07-24 22:31:00,0,0,0,0,0.0,0.0,35.0,24.8500,-80.6200,0,0,7
40019,913863,Gulf of mexico,marine thunderstorm wind,2020-07-26 22:50:00,EST-5,2020-07-26 22:50:00,0,0,0,0,0.0,0.0,35.0,24.4560,-81.8770,0,0,7
40020,913864,Gulf of mexico,marine thunderstorm wind,2020-07-31 21:30:00,EST-5,2020-07-31 21:30:00,0,0,0,0,0.0,0.0,35.0,24.8500,-80.6200,0,0,7
40021,913865,Gulf of mexico,marine thunderstorm wind,2020-07-31 22:00:00,EST-5,2020-07-31 22:00:00,0,0,0,0,0.0,0.0,34.0,24.8430,-80.8620,0,0,7
40022,913866,Gulf of mexico,marine thunderstorm wind,2020-07-31 22:40:00,EST-5,2020-07-31 22:40:00,0,0,0,0,0.0,0.0,34.0,24.6280,-81.1090,0,0,7
40023,913975,Gulf of mexico,marine thunderstorm wind,2020-07-12 19:30:00,CST-6,2020-07-12 19:31:00,0,0,0,0,0.0,0.0,41.0,30.5426,-87.9053,0,0,7
40024,913971,Gulf of mexico,marine thunderstorm wind,2020-07-12 17:17:00,CST-6,2020-07-12 17:18:00,0,0,0,0,0.0,0.0,37.0,30.4737,-87.1599,0,0,7
40025,913978,Gulf of mexico,marine thunderstorm wind,2020-07-12 20:24:00,CST-6,2020-07-12 20:25:00,0,0,0,0,0.0,0.0,55.0,30.2223,-88.0188,0,0,7
40026,913974,Gulf of mexico,marine thunderstorm wind,2020-07-12 19:17:00,CST-6,2020-07-12 19:18:00,0,0,0,0,0.0,0.0,50.0,30.6879,-88.0368,0,0,7
40027,913972,Gulf of mexico,marine thunderstorm wind,2020-07-12 17:32:00,CST-6,2020-07-12 17:33:00,0,0,0,0,0.0,0.0,34.0,30.3600,-87.0800,0,0,7
40028,913976,Gulf of mexico,marine thunderstorm wind,2020-07-12 19:34:00,CST-6,2020-07-12 19:35:00,0,0,0,0,0.0,0.0,40.0,30.6198,-88.0578,0,0,7
40029,913973,Gulf of mexico,marine thunderstorm wind,2020-07-12 18:33:00,CST-6,2020-07-12 18:34:00,0,0,0,0,0.0,0.0,36.0,30.3789,-86.4157,0,0,7
40030,913982,Gulf of mexico,marine thunderstorm wind,2020-07-08 17:07:00,CST-6,2020-07-08 17:08:00,0,0,0,0,0.0,0.0,37.0,30.4301,-87.9135,0,0,7
40031,913985,Gulf of mexico,marine thunderstorm wind,2020-07-22 13:46:00,CST-6,2020-07-22 13:47:00,0,0,0,0,0.0,0.0,43.0,30.3900,-86.5900,0,0,7
40032,913993,Gulf of mexico,marine thunderstorm wind,2020-07-24 13:34:00,CST-6,2020-07-24 13:35:00,0,0,0,0,0.0,0.0,37.0,30.4767,-86.3263,0,0,7
40033,913989,Gulf of mexico,marine thunderstorm wind,2020-07-23 11:47:00,CST-6,2020-07-23 11:48:00,0,0,0,0,0.0,0.0,41.0,30.6904,-88.0369,0,0,7
40034,913991,Gulf of mexico,marine thunderstorm wind,2020-07-23 11:53:00,CST-6,2020-07-23 11:54:00,0,0,0,0,0.0,0.0,35.0,30.6174,-88.0554,0,0,7
40035,913992,Gulf of mexico,marine thunderstorm wind,2020-07-24 11:12:00,CST-6,2020-07-24 11:13:00,0,0,0,0,0.0,0.0,36.0,30.2226,-88.0171,0,0,7
40036,913995,Gulf of mexico,marine thunderstorm wind,2020-07-25 14:00:00,CST-6,2020-07-25 14:01:00,0,0,0,0,0.0,0.0,34.0,30.4855,-86.4598,0,0,7

In [9]:
new_stormcsv.columns

Index(['event_id', 'state', 'event_type', 'event_begin_time', 'event_timezone',
       'event_end_time', 'injuries_direct', 'injuries_indirect',
       'deaths_direct', 'deaths_indirect', 'damage_property', 'damage_crops',
       'magnitude', 'event_latitude', 'event_longitude', 'Injuries', 'Deaths',
       'event_month'],
      dtype='object')

In [10]:
clean_storm = new_stormcsv[['event_id', 'state', 'event_type', 'event_month', 'event_begin_time', 'event_timezone',
       'event_end_time', 'Injuries', 'Deaths', 'damage_property', 'damage_crops',
       'magnitude', 'event_latitude', 'event_longitude']]
clean_storm.head()

,event_id,state,event_type,event_month,event_begin_time,event_timezone,event_end_time,Injuries,Deaths,damage_property,damage_crops,magnitude,event_latitude,event_longitude
0,865452,Oklahoma,hail,1,2020-01-10 11:35:00,CST-6,2020-01-10 11:35:00,0,0,0.0,0.0,1.00,36.1514,-95.9460
1,865453,Oklahoma,hail,1,2020-01-10 11:36:00,CST-6,2020-01-10 11:36:00,0,0,0.0,0.0,1.00,36.0690,-95.9585
2,865454,Oklahoma,hail,1,2020-01-10 11:38:00,CST-6,2020-01-10 11:38:00,0,0,0.0,0.0,0.75,36.1790,-95.9500
3,865455,Oklahoma,hail,1,2020-01-10 15:02:00,CST-6,2020-01-10 15:02:00,0,0,15000.0,0.0,1.75,35.9106,-94.9710
4,865712,Texas,hail,1,2020-01-10 19:40:00,CST-6,2020-01-10 19:40:00,0,0,0.0,0.0,0.75,30.2400,-98.1500

In [11]:
# column renamings

clean_storm = clean_storm.rename(columns={'Injuries':'total_injuries', 'Deaths':'total_deaths'})
clean_storm.head()

,event_id,state,event_type,event_month,event_begin_time,event_timezone,event_end_time,total_injuries,total_deaths,damage_property,damage_crops,magnitude,event_latitude,event_longitude
0,865452,Oklahoma,hail,1,2020-01-10 11:35:00,CST-6,2020-01-10 11:35:00,0,0,0.0,0.0,1.00,36.1514,-95.9460
1,865453,Oklahoma,hail,1,2020-01-10 11:36:00,CST-6,2020-01-10 11:36:00,0,0,0.0,0.0,1.00,36.0690,-95.9585
2,865454,Oklahoma,hail,1,2020-01-10 11:38:00,CST-6,2020-01-10 11:38:00,0,0,0.0,0.0,0.75,36.1790,-95.9500
3,865455,Oklahoma,hail,1,2020-01-10 15:02:00,CST-6,2020-01-10 15:02:00,0,0,15000.0,0.0,1.75,35.9106,-94.9710
4,865712,Texas,hail,1,2020-01-10 19:40:00,CST-6,2020-01-10 19:40:00,0,0,0.0,0.0,0.75,30.2400,-98.1500

In [12]:
clean_storm.dropna()
clean_storm.head()

,event_id,state,event_type,event_month,event_begin_time,event_timezone,event_end_time,total_injuries,total_deaths,damage_property,damage_crops,magnitude,event_latitude,event_longitude
0,865452,Oklahoma,hail,1,2020-01-10 11:35:00,CST-6,2020-01-10 11:35:00,0,0,0.0,0.0,1.00,36.1514,-95.9460
1,865453,Oklahoma,hail,1,2020-01-10 11:36:00,CST-6,2020-01-10 11:36:00,0,0,0.0,0.0,1.00,36.0690,-95.9585
2,865454,Oklahoma,hail,1,2020-01-10 11:38:00,CST-6,2020-01-10 11:38:00,0,0,0.0,0.0,0.75,36.1790,-95.9500
3,865455,Oklahoma,hail,1,2020-01-10 15:02:00,CST-6,2020-01-10 15:02:00,0,0,15000.0,0.0,1.75,35.9106,-94.9710
4,865712,Texas,hail,1,2020-01-10 19:40:00,CST-6,2020-01-10 19:40:00,0,0,0.0,0.0,0.75,30.2400,-98.1500

In [13]:
# # linking to StormsDB on SQL
# conn = "postgres:postgres@localhost:5432/storms_db"
# engine = create_engine(f'postgresql://{conn}')

In [14]:
# engine.table_names()

In [15]:
# clean_storm.to_sql(name='storms', con = engine, if_exists = 'replace', index = False)

In [16]:
#Run a query
# pd.read_sql_query('select * from storms limit 10', con = engine)

In [17]:
clean_storm.to_json(r'clean_storm.json',orient='table')

In [18]:
clean_storm.head()

,event_id,state,event_type,event_month,event_begin_time,event_timezone,event_end_time,total_injuries,total_deaths,damage_property,damage_crops,magnitude,event_latitude,event_longitude
0,865452,Oklahoma,hail,1,2020-01-10 11:35:00,CST-6,2020-01-10 11:35:00,0,0,0.0,0.0,1.00,36.1514,-95.9460
1,865453,Oklahoma,hail,1,2020-01-10 11:36:00,CST-6,2020-01-10 11:36:00,0,0,0.0,0.0,1.00,36.0690,-95.9585
2,865454,Oklahoma,hail,1,2020-01-10 11:38:00,CST-6,2020-01-10 11:38:00,0,0,0.0,0.0,0.75,36.1790,-95.9500
3,865455,Oklahoma,hail,1,2020-01-10 15:02:00,CST-6,2020-01-10 15:02:00,0,0,15000.0,0.0,1.75,35.9106,-94.9710
4,865712,Texas,hail,1,2020-01-10 19:40:00,CST-6,2020-01-10 19:40:00,0,0,0.0,0.0,0.75,30.2400,-98.1500

In [31]:
# Making new group_by dataframe to summarize our data by state and month and get counts for each category to use for our bar chart
# Need count by state and month of event_id
storm_group_bar = clean_storm.groupby(["state","event_month"]).count()['event_id']
storm_group_bardf = storm_group.to_frame()
storm_group_bardf.head(20)

                            event_id
state          event_month
Alabama        1                 157
               2                 124
               3                  96
               4                 390
               5                 101
               6                 101
               7                 134
Alaska         1                  59
               2                  60
               3                  24
               4                  22
               5                   2
               7                   1
American samoa 1                   3
               2                  14
               3                   1
               4                   1
               6                   2
               7                   1
Arizona        1                   2

In [32]:
clean_storm.columns

Index(['event_id', 'state', 'event_type', 'event_month', 'event_begin_time',
       'event_timezone', 'event_end_time', 'total_injuries', 'total_deaths',
       'damage_property', 'damage_crops', 'magnitude', 'event_latitude',
       'event_longitude'],
      dtype='object')

In [38]:
# Creating 2nd grouped dataframe to see counts of below categories by state
# Need count by state and event_type

storm_group_pie = clean_storm.groupby(["state","event_type"]).count()['event_id']
storm_group_piedf = storm_group_pie.to_frame()
storm_group_piedf.head(20)

                                 event_id
state   event_type
Alabama flash flood                    77
        flood                          40
        frost/freeze                    4
        hail                           57
        heat                           11
        heavy rain                      1
        high wind                      12
        lightning                       4
        storm surge/tide                4
        strong wind                     8
        thunderstorm wind             806
        tornado                        71
        tropical storm                  3
        winter weather                  5
Alaska  avalanche                       3
        blizzard                       53
        cold/wind chill                 7
        extreme cold/wind chill         1
        flood                           7
        heavy snow                     57

In [ ]:
# Creating 3rd grouped dataframe to see counts of below categories by state
# Need count by state with only 4 damage columns (total deaths, total injuries, damage property, damage crops)
# Need count by state and event_type

storm_group_bubblepie = clean_storm.groupby("state").count()['event_type'].sum()[['total_injuries', 'total_deaths',
       'damage_property', 'damage_crops']]
storm_group_bubblepie.head(20)